# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixSqrt <- function(orig) {
    .Call(`_MatrixTests_matrixSqrt`, orig)
}

vectorSum <- function(x) {
    .Call(`_MatrixTests_vectorSum`, x)
}

parallelMatrixSqrt <- function(orig) {
    .Call(`_MatrixTests_parallelMatrixSqrt`, orig)
}

parallelVectorSum <- function(x) {
    .Call(`_MatrixTests_parallelVectorSum`, x)
}

